process.chdir(require('path').resolve(__dirname,'..'));
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const c=vm.createContext({window:{},localStorage:{getItem:()=>null},document:{addEventListener:()=>{}},wingCanonicalId:id=>id,potionAttributes:()=>'',wingProfile:()=>'',recoverySummary:()=>''});
for(const f of ['data.js','attributes.js','scroll-variants.js','item-stats.js','equipment-filters.js'])vm.runInContext(fs.readFileSync('site/'+f,'utf8'),c);
const app=fs.readFileSync('site/app.js','utf8');vm.runInContext(app.slice(0,app.indexOf('const mechanics=')),c);
for(const line of app.split('\n'))if(['function itemHTML(','function itemImages(','function paginate(','function filterChips('].some(prefix=>line.startsWith(prefix)))vm.runInContext(line,c);
const d=JSON.parse(fs.readFileSync('site/catalog.json','utf8')),audit=JSON.parse(fs.readFileSync('site/scroll-variants-audit.json','utf8'));
const scrolls=d.items.filter(x=>x.enchantment);assert.equal(scrolls.length,52);
for(const x of scrolls){const profile=vm.runInContext(`scrollProfiles[${x.id}]`,c);assert.deepEqual(Array.from(profile.monsterIds),d.monsters.filter(m=>m.loot.includes(x.id)).map(m=>m.id));assert.equal(profile.boss,profile.monsterIds.some(id=>d.monsters.find(m=>m.id===id).boss));c.x=x;assert.equal(vm.runInContext('itemCategory(x)',c),'monster-scrolls');}
assert.equal(Object.values(audit.profiles).filter(p=>p.boss).length,10);
for(const pair of audit.pairs){const a=d.items.find(x=>x.id===pair.physical),b=d.items.find(x=>x.id===pair.magic),stats=a.enchantment.stats.slice();for(const [lo,hi] of [[3,6],[5,7],[8,10],[9,11]])[stats[lo],stats[hi]]=[stats[hi],stats[lo]];assert.deepEqual(stats,b.enchantment.stats);assert.equal(a.enchantment.slot,b.enchantment.slot);assert.equal(pair.kind==='variant',a.name.en===b.name.en);for(const id of [pair.physical,pair.magic]){const p=audit.profiles[id];assert.equal(audit.profiles[p.counterpart].counterpart,id);assert.equal(id===pair.physical?p.tone==='physical':p.tone==='magic',true);}}
for(const lang of ['ru','en']){vm.runInContext(`lang=${JSON.stringify(lang)};category='monster-scrolls';Object.assign(equipmentFilters,{classId:'7',maxLevel:'1'})`,c);const rows=vm.runInContext('equipmentFilteredItems()',c);assert.equal(rows.length,52);assert.equal(vm.runInContext('equipmentFilterHTML()',c),'');c.rows=rows;const html=vm.runInContext('equipmentItemsHTML(rows)',c);const ids=Array.from(html.matchAll(/data-detail="item" data-id="(\d+)"/g),m=>Number(m[1]));assert.equal(ids.indexOf(70047),ids.indexOf(70034)+1);assert(html.includes('scroll-catalog'));for(const id of [70034,70047,70031,70026,70044,70043,70049,70050]){c.x=d.items.find(x=>x.id===id);const card=vm.runInContext('itemHTML(x)',c),detail=vm.runInContext('itemCharacteristics(x)',c);assert(card.includes('scroll-variant'));assert(card.includes('#'+audit.profiles[id].counterpart));assert(detail.includes(`data-id="${audit.profiles[id].counterpart}"`));assert(!/Успех|Плата|Success|Fee/.test(card));}vm.runInContext("category='scrolls'",c);assert.equal(vm.runInContext('equipmentFilteredItems()',c).length,116);assert(vm.runInContext('equipmentFilteredItems()',c).every(x=>!x.enchantment));}
console.log('PASS variants: 52 exact loot associations, 10 boss drops, one same-name pair, three reciprocal damage analogues, separated recipes, adjacent variants and RU/EN details.');
